[project]
name = "gapminder-project"
version = "0.1.0"
description = "Gapminder Project: Reproducible Workflow with Pixi.sh"
authors = ["Aziz Khan <azizk@stanford.edu>"]
channels = ["conda-forge"]
platforms = ["osx-arm64","linux-64", "win-64", "osx-64"]

[tasks]
preprocess = "python src/scripts/preprocess.py"
analyze = "python src/scripts/analysis.py"
visualize = "python src/scripts/visualize.py"

[dependencies]
python = "3.9.*"
pandas = ">=2.2.3,<3"
numpy = ">=2.0.2,<3"
matplotlib = ">=3.9.3,<4"
seaborn = ">=0.13.2,<0.14"
jupyterlab = ">=4.3.2,<5"
